# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sg-util.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGraphicsView,
    QLabel, QMainWindow, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(207, 250)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(207)
        sizePolicy.setVerticalStretch(31)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(207, 250))
        MainWindow.setMaximumSize(QSize(207, 250))
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.WindowSelecter = QComboBox(self.centralwidget)
        self.WindowSelecter.setObjectName(u"WindowSelecter")
        self.WindowSelecter.setGeometry(QRect(89, 11, 101, 22))
        self.WindowSelecter.setLayoutDirection(Qt.LeftToRight)
        self.WindowSelecter.setEditable(False)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(11, 11, 72, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 71, 20))
        self.CurrentRolePicture = QGraphicsView(self.centralwidget)
        self.CurrentRolePicture.setObjectName(u"CurrentRolePicture")
        self.CurrentRolePicture.setGeometry(QRect(70, 40, 121, 21))
        self.CurrentRolePicture.setLineWidth(8)
        self.CurrentRolePicture.setInteractive(False)
        self.CurrentBloodPicture = QGraphicsView(self.centralwidget)
        self.CurrentBloodPicture.setObjectName(u"CurrentBloodPicture")
        self.CurrentBloodPicture.setGeometry(QRect(30, 70, 121, 21))
        self.EnableBloodHelper = QCheckBox(self.centralwidget)
        self.EnableBloodHelper.setObjectName(u"EnableBloodHelper")
        self.EnableBloodHelper.setGeometry(QRect(10, 70, 13, 13))
        self.EnableBloodHelper.setChecked(True)
        self.MinBloodPrecentageSelecter = QComboBox(self.centralwidget)
        self.MinBloodPrecentageSelecter.addItem("")
        self.MinBloodPrecentageSelecter.addItem("")
        self.MinBloodPrecentageSelecter.addItem("")
        self.MinBloodPrecentageSelecter.addItem("")
        self.MinBloodPrecentageSelecter.setObjectName(u"MinBloodPrecentageSelecter")
        self.MinBloodPrecentageSelecter.setGeometry(QRect(30, 100, 41, 22))
        self.EnableMagicHelper = QCheckBox(self.centralwidget)
        self.EnableMagicHelper.setObjectName(u"EnableMagicHelper")
        self.EnableMagicHelper.setGeometry(QRect(10, 130, 16, 20))
        self.EnableMagicHelper.setChecked(True)
        self.CurrentMagicPicture = QGraphicsView(self.centralwidget)
        self.CurrentMagicPicture.setObjectName(u"CurrentMagicPicture")
        self.CurrentMagicPicture.setGeometry(QRect(30, 130, 121, 21))
        self.MinBloodKeySelecter = QComboBox(self.centralwidget)
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem(u"A")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.addItem("")
        self.MinBloodKeySelecter.setObjectName(u"MinBloodKeySelecter")
        self.MinBloodKeySelecter.setGeometry(QRect(160, 70, 31, 21))
        self.MinBloodKeySelecter.setLayoutDirection(Qt.LeftToRight)
        self.MinBloodKeySelecter.setEditable(False)
        self.MinMagicKeySelecter = QComboBox(self.centralwidget)
        self.MinMagicKeySelecter.addItem("")
        self.MinMagicKeySelecter.addItem("")
        self.MinMagicKeySelecter.addItem("")
        self.MinMagicKeySelecter.setObjectName(u"MinMagicKeySelecter")
        self.MinMagicKeySelecter.setGeometry(QRect(160, 130, 31, 21))
        self.MinMagicKeySelecter.setLayoutDirection(Qt.LeftToRight)
        self.MinMagicKeySelecter.setEditable(False)
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 100, 16, 16))
        self.Tick1 = QComboBox(self.centralwidget)
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.addItem("")
        self.Tick1.setObjectName(u"Tick1")
        self.Tick1.setGeometry(QRect(30, 160, 69, 22))
        self.Tick2 = QComboBox(self.centralwidget)
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.addItem("")
        self.Tick2.setObjectName(u"Tick2")
        self.Tick2.setGeometry(QRect(110, 160, 69, 22))
        self.Tick3 = QComboBox(self.centralwidget)
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.addItem("")
        self.Tick3.setObjectName(u"Tick3")
        self.Tick3.setGeometry(QRect(30, 190, 69, 22))
        self.Tick4 = QComboBox(self.centralwidget)
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.addItem("")
        self.Tick4.setObjectName(u"Tick4")
        self.Tick4.setGeometry(QRect(110, 190, 69, 22))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u4e09\u56fd\u9b54\u624b", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u8bf7\u9009\u62e9\u7a97\u53e3\uff1a", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u5f53\u524d\u89d2\u8272\uff1a", None))
        self.EnableBloodHelper.setText("")
        self.MinBloodPrecentageSelecter.setItemText(0, QCoreApplication.translate("MainWindow", u"40", None))
        self.MinBloodPrecentageSelecter.setItemText(1, QCoreApplication.translate("MainWindow", u"20", None))
        self.MinBloodPrecentageSelecter.setItemText(2, QCoreApplication.translate("MainWindow", u"60", None))
        self.MinBloodPrecentageSelecter.setItemText(3, QCoreApplication.translate("MainWindow", u"80", None))

        self.EnableMagicHelper.setText("")
        self.MinBloodKeySelecter.setItemText(0, QCoreApplication.translate("MainWindow", u"E", None))
        self.MinBloodKeySelecter.setItemText(2, QCoreApplication.translate("MainWindow", u"B", None))
        self.MinBloodKeySelecter.setItemText(3, QCoreApplication.translate("MainWindow", u"C", None))
        self.MinBloodKeySelecter.setItemText(4, QCoreApplication.translate("MainWindow", u"D", None))
        self.MinBloodKeySelecter.setItemText(5, QCoreApplication.translate("MainWindow", u"Q", None))
        self.MinBloodKeySelecter.setItemText(6, QCoreApplication.translate("MainWindow", u"W", None))
        self.MinBloodKeySelecter.setItemText(7, QCoreApplication.translate("MainWindow", u"R", None))
        self.MinBloodKeySelecter.setItemText(8, QCoreApplication.translate("MainWindow", u"T", None))

        self.MinMagicKeySelecter.setItemText(0, QCoreApplication.translate("MainWindow", u"R", None))
        self.MinMagicKeySelecter.setItemText(1, QCoreApplication.translate("MainWindow", u"E", None))
        self.MinMagicKeySelecter.setItemText(2, QCoreApplication.translate("MainWindow", u"T", None))

        self.label_3.setText(QCoreApplication.translate("MainWindow", u"%", None))
        self.Tick1.setItemText(0, "")
        self.Tick1.setItemText(1, QCoreApplication.translate("MainWindow", u"A", None))
        self.Tick1.setItemText(2, QCoreApplication.translate("MainWindow", u"B", None))
        self.Tick1.setItemText(3, QCoreApplication.translate("MainWindow", u"C", None))
        self.Tick1.setItemText(4, QCoreApplication.translate("MainWindow", u"D", None))
        self.Tick1.setItemText(5, QCoreApplication.translate("MainWindow", u"Q", None))
        self.Tick1.setItemText(6, QCoreApplication.translate("MainWindow", u"W", None))
        self.Tick1.setItemText(7, QCoreApplication.translate("MainWindow", u"E", None))
        self.Tick1.setItemText(8, QCoreApplication.translate("MainWindow", u"R", None))
        self.Tick1.setItemText(9, QCoreApplication.translate("MainWindow", u"T", None))

        self.Tick2.setItemText(0, "")
        self.Tick2.setItemText(1, QCoreApplication.translate("MainWindow", u"A", None))
        self.Tick2.setItemText(2, QCoreApplication.translate("MainWindow", u"B", None))
        self.Tick2.setItemText(3, QCoreApplication.translate("MainWindow", u"C", None))
        self.Tick2.setItemText(4, QCoreApplication.translate("MainWindow", u"D", None))
        self.Tick2.setItemText(5, QCoreApplication.translate("MainWindow", u"Q", None))
        self.Tick2.setItemText(6, QCoreApplication.translate("MainWindow", u"W", None))
        self.Tick2.setItemText(7, QCoreApplication.translate("MainWindow", u"E", None))
        self.Tick2.setItemText(8, QCoreApplication.translate("MainWindow", u"R", None))
        self.Tick2.setItemText(9, QCoreApplication.translate("MainWindow", u"T", None))

        self.Tick3.setItemText(0, "")
        self.Tick3.setItemText(1, QCoreApplication.translate("MainWindow", u"A", None))
        self.Tick3.setItemText(2, QCoreApplication.translate("MainWindow", u"B", None))
        self.Tick3.setItemText(3, QCoreApplication.translate("MainWindow", u"C", None))
        self.Tick3.setItemText(4, QCoreApplication.translate("MainWindow", u"D", None))
        self.Tick3.setItemText(5, QCoreApplication.translate("MainWindow", u"Q", None))
        self.Tick3.setItemText(6, QCoreApplication.translate("MainWindow", u"W", None))
        self.Tick3.setItemText(7, QCoreApplication.translate("MainWindow", u"E", None))
        self.Tick3.setItemText(8, QCoreApplication.translate("MainWindow", u"R", None))
        self.Tick3.setItemText(9, QCoreApplication.translate("MainWindow", u"T", None))

        self.Tick4.setItemText(0, "")
        self.Tick4.setItemText(1, QCoreApplication.translate("MainWindow", u"A", None))
        self.Tick4.setItemText(2, QCoreApplication.translate("MainWindow", u"B", None))
        self.Tick4.setItemText(3, QCoreApplication.translate("MainWindow", u"C", None))
        self.Tick4.setItemText(4, QCoreApplication.translate("MainWindow", u"D", None))
        self.Tick4.setItemText(5, QCoreApplication.translate("MainWindow", u"Q", None))
        self.Tick4.setItemText(6, QCoreApplication.translate("MainWindow", u"W", None))
        self.Tick4.setItemText(7, QCoreApplication.translate("MainWindow", u"E", None))
        self.Tick4.setItemText(8, QCoreApplication.translate("MainWindow", u"R", None))
        self.Tick4.setItemText(9, QCoreApplication.translate("MainWindow", u"T", None))

    # retranslateUi

